[workspace]

members = [
    "variables",
    "primitive_type", 
    "control_flow", "ownership", "struct_instance", "Enum", "match_iflet", "module", "collection", "error_handling", "generics", "lifetime", "auto_test",
]
